USE jxsk

INSERT INTO C VALUES('C1','程序设计','60')
select * from c

UPDATE T SET PROF='教授' WHERE TN ='张兰'
select * from t
WHERE TN ='张兰'

DELETE FROM T WHERE TN ='张兰'

SELECT * INTO test1 FROM S

Select TN,SEX,AGE,PROF into test2 From T
where sex ='男'

ALTER TABLE T
ADD CONSTRAINT PK_TNO PRIMARY KEY(TNO)

alter table t
alter column  tno char(10) not null

CREATE TABLE TEST_C(
CNO CHAR(2) CONSTRAINT PK_TEST_C PRIMARY KEY,
CN CHAR(10),
CT TINYINT)

CREATE TABLE TEST_TC(
TNO CHAR(2) ,
CNO CHAR(2) ,
CONSTRAINT PK_TEST_TC PRIMARY KEY(TNO, CNO))

CREATE TABLE cn
(
UNIQUE_c int NOT NULL,

UNIQUE (UNIQUE_c)
)


ALTER TABLE TEST_TC
ADD ID_TC INT IDENTITY
ALTER TABLE C DROP UNIQUE_C

ALTER TABLE S WITH CHECK
ADD CONSTRAINT CHECK_AGE CHECK( AGE>=14 AND AGE<=40)

CREATE TABLE TEST_S(
SNO CHAR(2) NOT NULL,
SN CHAR(8) NOT NULL,
SEX CHAR(2) NULL CONSTRAINT DEFAULT_SEX DEFAULT '男'
CONSTRAINT CHECK_SEX CHECK(SEX='男' OR SEX='女'),
AGE TINYINT NULL CONSTRAINT DEFAULT_AGE1 DEFAULT 18,
CONSTRAINT CHECK_S_AGE1 CHECK(AGE>=14 AND AGE<=40)
)
ALTER TABLE TC  
ADD CONSTRAINT FK_T_TC FOREIGN KEY (TN) REFERENCES T(TN)
